### PR TITLE
Notes and asm fixes for "erase" functions

### PR DESCRIPTION
**Pull request by quietboil**
- Added comments to the 3 flash erase functions. Sector Erase is the most commented as that's where I started.
- Fixed the "static" function <sub_40c0> (new name <esp_spi_erase_sector>) that had a section where disassembler stuttered a bit.
- Added (second commit) comments to the `SPIRead` (mostly to the sub that does the job)

### CODE REVIEW

**Comment by quietboil** [comment]
- Added (more) notes to `SPIRead` (mostly to the sub that does the work)

**Comment by trebisky** [comment]
Hey, I didn't mean to ignore this, but clearly I did.  And I ain't never responded to a pull request yet, so If I can figure out how to deal with this, I'll merge your changes (and thanks for them).

**Comment by trebisky** [comment]
I started disassembling the esp32 bootrom and worked up a much better disassembler scheme that I could retrofit to the esp8266 and do a much better job, likely it would not "stutter", but who knows.  But who knows when I will get around to that retrofit, so I'll just try to grab your fixes.  Heck if I can find and clone your repo, I'll just hand merge what you have done.

**Comment by trebisky** [comment]
Or send an email (and send the bootrom.txt you have made changes to, or if you want, the section you modified, and I'll merge it in by hand).  Or reactivate the pull request and it will be a good chance for me to learn some new tricks.

**Comment by quietboil** [comment]
No worries, I'll send a new pull request. In a day or two though. Some other activities are awaiting - :fireworks: :cake: :smile:

**Comment by trebisky** [comment]
I just redid the bootrom disassembly using this new multipass script I wrote for the ESP32.  If you see anything that doesn't look quite right, let me know. I had to write another script to migrate all the comments from the old disassembly.   This cleans up a lot of the misdisassembled sections.

**Pull request closed without merging**
